import React from 'react';

import type { Metadata } from 'next';
import Navbar from './_components/Navbar';
import Footer from './_components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className='h-full bg-gray-700 flex flex-col'>
      <Navbar />
      <div className='flex-1'>{children}</div>
      <Footer />
    </main>
  );
}
